[build]
  command = "npm install -g @angular/cli && npm ci && npm run build"
  publish = "dist/front-project"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20.12.2"

[[plugins]]
  package = "@netlify/angular-runtime"

[build.processing]
  skip_processing = true