export interface PatientInterface {
    _id: string,
    name: string,
    age: number,
    date_of_birth: string,
    address: string,
    education: string,
    profession: string,
    marital_status: string,
    phone: string,
    emergency_contact: string,
    ethnicity: string,
    children: boolean,
    many: number,
    naturalness: string,
    sex: string,
    email: string,
    phone_number: number,
    height: string,
    weight: string,
    postal_code: string,
	address_number: number,
	complement: string,
	province: string,
	city: string,
	uf: string,
}